### ISSUE TITLE
MT资源连接获取失败

### ISSUE THREAD

**Issue by warlocks365** [linyuan0213/nas-tools#54]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: 3.5.5
>
> 环境: docker Synology
>

## 你遇到什么问题了？

> 最近两天突然发现下载MT的资源会弹出获取连接失败，并给出连接地址。但可以通过标题直接跳转到MT的对应帖子上。经过与原帖下载地址对比发现是NAStool获取的地址头部少了一个/导致的（【mteam】Transformers Prime Complete BluRay 1080p x264-TFSub 添加下载失败 无法打开链接：https://ds1.m-team.co?app_id=）括弧里是报错信息的一部分，错误位置就是最后那个？前面少了一个/。其他站点的下载没有遇到类似问题。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 希望更新该错误。

## 给出程序界面截图、后台运行日志或配置文件

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by linyuan0213** [comment]
提供下日志

**Comment by warlocks365** [comment]
> 正常来说馒头获取到的下载地址应该是像这样 /api/rss/dlv2?useHttps=true&type=ipv4&sign=4271b5e9xxx,不应该是你这种

我手动去MT网站下载种子的地址的确是我上面那种格式。而NASTool的报错也确实是就少了一个/，奇怪的是我用的一直是docker部署，并没有更改配置，故障的前一天我还可以正常下载MT的种子。我尝试了矿神的NASTool，是可以正常获取种子的，站点配置完全一样。我也尝试过重新配置MT站点，但故障依旧。我十分困惑。

**Comment by linyuan0213** [comment]
你把这个链接放到 qb 里看能不能下载到在 2024年8月8日，23:42，warlocks365 ***@***.***> 写道：﻿

正常来说馒头获取到的下载地址应该是像这样 /api/rss/dlv2?useHttps=true&type=ipv4&sign=4271b5e9xxx,不应该是你这种

我手动去MT网站下载种子的地址的确是我上面那种格式。而NASTool的报错也确实是就少了一个/，奇怪的是我用的一直是docker部署，并没有更改配置，故障的前一天我还可以正常下载MT的种子。我尝试了矿神的NASTool，是可以正常获取种子的，站点配置完全一样。我也尝试过重新配置MT站点，但故障依旧。我十分困惑。

**Comment by warlocks365** [comment]
> 你把这个链接放到 qb 里看能不能下载到在 2024年8月8日，23:42，warlocks365 ***@***.***> 写道：﻿ 正常来说馒头获取到的下载地址应该是像这样 /api/rss/dlv2?useHttps=true&type=ipv4&sign=4271b5e9xxx,不应该是你这种 我手动去MT网站下载种子的地址的确是我上面那种格式。而NASTool的报错也确实是就少了一个/，奇怪的是我用的一直是docker部署，并没有更改配置，故障的前一天我还可以正常下载MT的种子。我尝试了矿神的NASTool，是可以正常获取种子的，站点配置完全一样。我也尝试过重新配置MT站点，但故障依旧。我十分困惑。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

我确实手动尝试过了，不论是不是在报错地址上添加/，都不能正确下载。手工点MT页面上的连接是没问题的。但MT上的用浏览器直接获得的种子连接也的确不是你给出的格式，我估计应该是因为NASTool使用的是API获取，和网页上的链接地址并不一样。但我的问题依然没有解决。哭

**Comment by linyuan0213** [comment]
你在馒头的控制台里换个种子下载地址试试，不行我再看看在 2024年8月9日，18:18，warlocks365 ***@***.***> 写道：﻿

你把这个链接放到 qb 里看能不能下载到在 2024年8月8日，23:42，warlocks365 @.> 写道：﻿ 正常来说馒头获取到的下载地址应该是像这样 /api/rss/dlv2?useHttps=true&type=ipv4&sign=4271b5e9xxx,不应该是你这种 我手动去MT网站下载种子的地址的确是我上面那种格式。而NASTool的报错也确实是就少了一个/，奇怪的是我用的一直是docker部署，并没有更改配置，故障的前一天我还可以正常下载MT的种子。我尝试了矿神的NASTool，是可以正常获取种子的，站点配置完全一样。我也尝试过重新配置MT站点，但故障依旧。我十分困惑。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.>

我确实手动尝试过了，不论是不是在报错地址上添加/，都不能正确下载。手工点MT页面上的连接是没问题的。但MT上的用浏览器直接获得的种子连接也的确不是你给出的格式，我估计应该是因为NASTool使用的是API获取，和网页上的链接地址并不一样。但我的问题依然没有解决。哭

**Comment by warlocks365** [comment]
> 你在馒头的控制台里换个种子下载地址试试，不行我再看看在 2024年8月9日，18:18，warlocks365 ***@***.***> 写道：﻿ 你把这个链接放到 qb 里看能不能下载到在 2024年8月8日，23:42，warlocks365 @.> 写道：﻿ 正常来说馒头获取到的下载地址应该是像这样 /api/rss/dlv2?useHttps=true&type=ipv4&sign=4271b5e9xxx,不应该是你这种 我手动去MT网站下载种子的地址的确是我上面那种格式。而NASTool的报错也确实是就少了一个/，奇怪的是我用的一直是docker部署，并没有更改配置，故障的前一天我还可以正常下载MT的种子。我尝试了矿神的NASTool，是可以正常获取种子的，站点配置完全一样。我也尝试过重新配置MT站点，但故障依旧。我十分困惑。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.> 我确实手动尝试过了，不论是不是在报错地址上添加/，都不能正确下载。手工点MT页面上的连接是没问题的。但MT上的用浏览器直接获得的种子连接也的确不是你给出的格式，我估计应该是因为NASTool使用的是API获取，和网页上的链接地址并不一样。但我的问题依然没有解决。哭 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

仍然不行，手工从MT网页获取的种子都可以正常下载，但是从NASTOOLS上只要是MT的种子都获取失败了。其他站点的种子都是正常的。我甚至已经重新添加的MT的站点信息，连api令牌都重新申请了一个新的。依然故障依旧。我用的白群的Docker部署的。这个docker已经稳定运行很久了。这个故障时突然出现的，非常莫名其妙。

**Comment by linyuan0213** [comment]
这个应该是馒头更新什么导致的，我这几天看看具体什么问题在 2024年8月10日，23:00，warlocks365 ***@***.***> 写道：﻿

你在馒头的控制台里换个种子下载地址试试，不行我再看看在 2024年8月9日，18:18，warlocks365 @.> 写道：﻿ 你把这个链接放到 qb 里看能不能下载到在 2024年8月8日，23:42，warlocks365 @.> 写道：﻿ 正常来说馒头获取到的下载地址应该是像这样 /api/rss/dlv2?useHttps=true&type=ipv4&sign=4271b5e9xxx,不应该是你这种 我手动去MT网站下载种子的地址的确是我上面那种格式。而NASTool的报错也确实是就少了一个/，奇怪的是我用的一直是docker部署，并没有更改配置，故障的前一天我还可以正常下载MT的种子。我尝试了矿神的NASTool，是可以正常获取种子的，站点配置完全一样。我也尝试过重新配置MT站点，但故障依旧。我十分困惑。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.> 我确实手动尝试过了，不论是不是在报错地址上添加/，都不能正确下载。手工点MT页面上的连接是没问题的。但MT上的用浏览器直接获得的种子连接也的确不是你给出的格式，我估计应该是因为NASTool使用的是API获取，和网页上的链接地址并不一样。但我的问题依然没有解决。哭 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: @.>

仍然不行，手工从MT网页获取的种子都可以正常下载，但是从NASTOOLS上只要是MT的种子都获取失败了。其他站点的种子都是正常的。我甚至已经重新添加的MT的站点信息，连api令牌都重新申请了一个新的。依然故障依旧。我用的白群的Docker部署的。这个docker已经稳定运行很久了。这个故障时突然出现的，非常莫名其妙。

**Comment by HHr06** [comment]
> 正常来说馒头获取到的下载地址应该是像这样 /api/rss/dlv2?useHttps=true&type=ipv4&sign=4271b5e9xxx,不应该是你这种

同样遇到了这个问题，报错信息是
`【Brush】M-Team 刷流 添加下载任务出错：....，错误原因：无法打开链接：https://ds1.m-team.co?app_id=1&playload=.....，种子链接：https://api.m-team.cc/api/rss/dlv2?sign=....`

**Comment by linyuan0213** [comment]
> > 正常来说馒头获取到的下载地址应该是像这样 /api/rss/dlv2?useHttps=true&type=ipv4&sign=4271b5e9xxx,不应该是你这种
> 
> 同样遇到了这个问题，报错信息是 `【Brush】M-Team 刷流 添加下载任务出错：....，错误原因：无法打开链接：https://ds1.m-team.co?app_id=1&playload=.....，种子链接：https://api.m-team.cc/api/rss/dlv2?sign=....`

我这两天排查下这个问题

**Comment by linyuan0213** [comment]
> > 正常来说馒头获取到的下载地址应该是像这样 /api/rss/dlv2?useHttps=true&type=ipv4&sign=4271b5e9xxx,不应该是你这种
> 
> 同样遇到了这个问题，报错信息是 `【Brush】M-Team 刷流 添加下载任务出错：....，错误原因：无法打开链接：https://ds1.m-team.co?app_id=1&playload=.....，种子链接：https://api.m-team.cc/api/rss/dlv2?sign=....`

<img width="476" alt="image" src="https://github.com/user-attachments/assets/bf475ee8-b74f-4a40-9412-51ef1485fb8d">
在控制台换其他域名试试，看起来是和这个有关，部分地区访问m-team.co这个域名可能有点问题

**Comment by warlocks365** [comment]
> > > 正常来说馒头获取到的下载地址应该是像这样 /api/rss/dlv2?useHttps=true&type=ipv4&sign=4271b5e9xxx,不应该是你这种
> > 
> > 
> > 同样遇到了这个问题，报错信息是 `【Brush】M-Team 刷流 添加下载任务出错：....，错误原因：无法打开链接：https://ds1.m-team.co?app_id=1&playload=.....，种子链接：https://api.m-team.cc/api/rss/dlv2?sign=....`
> 
> <img alt="image" width="476" src="https://private-user-images.githubusercontent.com/26356991/358846984-bf475ee8-b74f-4a40-9412-51ef1485fb8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5OTEzMjAsIm5iZiI6MTcyMzk5MTAyMCwicGF0aCI6Ii8yNjM1Njk5MS8zNTg4NDY5ODQtYmY0NzVlZTgtYjc0Zi00YTQwLTk0MTItNTFlZjE0ODVmYjhkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE4VDE0MjM0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiYzMxNjVhZmVjZDBkMGI4ZmU3ZDJlZmZjMDk4NzdkZDQ5MzhkZjVjNWMyZDdmYWRjOTQ3Y2JhZTM0ODRiYmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jdnoOSfx9qh6YK7fa93952-UpUpAxgtkYWMY3a_qL2A"> 在控制台换其他域名试试，看起来是和这个有关，部分地区访问m-team.co这个域名可能有点问题

按照你的建议进行了设置后果然可以正常下载种子了，多谢！
